### ISSUE TITLE
Is there any example application using teltonika-fm-parser?

### ISSUE THREAD

**Issue by 8parth** [uro/teltonika-fm-parser#1]
I have not worked with php, but the library can help me parse data coming from teltonika devices and would like to use it. Some example application or guide for using the library in php would be of great help in integration.

**Comment by uro** [comment]
Hello @8parth. 

First of all, I'm sorry for this late reply. For now, there is no public example of usage.
It's very good idea, I'll try to create it in first spare time - or we can do that together, feel free to submit pull request :)

**Comment by 8parth** [comment]
I will sure try and generate a pull request for the same. Any information about teltonika simulator would be helpful.

**Comment by jreisam** [comment]
Guys I'm using "quantumstrings" solution, it works perfectly and you can listen/parse using it. 
https://github.com/quantumstrings/GPS-Listener-Parser ( Visual Studio C#)

**Comment by cf-git** [comment]
For one project i did use this library, but this not work with custom data. So i did create, a simple functions for this task, but for this need up tcp socket server. So if u need i can try find functions in my cloud

**Comment by uro** [comment]
Hey @cf-git 
As first, thank you for using this library. Custom data are not implemented yet as it was not important to me. If you have the code related to this, feel free to share pull request, I'll be happy to add it. 
If you don't have code, then please share your functions. With it I can easily add custom data functionality to this library. 

It will be better then :)

**Comment by cf-git** [comment]
Ok. I can't do the implementation for this lib right now, but i found file with functions based on this lib with added custom fields implementation. So i put link to this file here, and if u can implement it will be great.

https://github.com/cf-git/teltonika-functions/blob/master/teltonika.php

I don't know about current changes of teltonika protocol and i think that i use actual. But if u need example of usage, i can try build it later, because i can't find full version of this code.
Please, write me on this issue if it is. 

Thank u :)

**Comment by gricob** [comment]
I've just pushed v2 to my fork which includes a TCP example on readme file. 
This release includes:
- CRC validation
- IOElement
- Codec8 Extended support

The bad new is that is not compatible with v1. It would be nice to keep v1 in a separated branch and merge v2 to continue improving the package. What do you think about it?

**Comment by uro** [comment]
Hello @gricob, wow! 🥇 

Thank you for your amazing work. Your contribution will push this library forward.

I did not use my Teltonika device for a while. Please, submit a pr - we will review it and merge. 
We should definitely merge it somehow, but we should find a way to keep backward compatibility with the v1 version. I didn't check it yet but I hope some adapters can solve the issue - don't worry, we will work it out somehow. 

I'll have some free time during the weekend, let's crack it on!

**Comment by uro** [comment]
Late reply. 

A simple example is available in the readme. 
Thank you @gricob, again. 

Trying to clean up this mess. Please ping me if you have queries.

**Comment by uro** [comment]
Closing down as it seems to be sorted.

**Comment by harshwebdev22** [comment]
Please anyone can provide the code to parse teltonika device data?
I need device data like imei long lat event id speed battery info etc etc

**Comment by harshwebdev22** [comment]
Can someone please share code to parse Teltonika device data? I'm looking to extract details like IMEI, latitude, longitude, event ID, speed, battery information, and more. Any help would be greatly appreciated!
