### ISSUE TITLE
Understanding how this works

### ISSUE THREAD

**Issue by DanJamesMills** [uro/teltonika-fm-parser#6]
Hi All,

I'm trying to figure out how all this works I have an FMT100, that I want to read the acl packet and parse it.

Does this library provide a TCP server for the fmt100 to connect to?

**Comment by uro** [comment]
Hello @DanJamesMills 

This library decodes and encodes the data in order to talk to the teltonika devices. 

The point was to keep it clean from the dependencies, so you can connect it to any server, and any model/database. 

There is one simple example in the docs. It might be helpful

**Comment by DanJamesMills** [comment]
Hi @uro,

Many thanks for coming back to me I kind of figured it out, I've been using react/socket as my TCP server to received the data from the tracker and your library then to decode it, so far it seems to work fine. Great work!

**Comment by uro** [comment]
Happy to hear this.

Closing the issue for now.
