### ISSUE TITLE
Not getting Proper data

### ISSUE THREAD

**Issue by Nimesh-Soni** [uro/teltonika-fm-parser#7]
hello,
I have static data getting from device in Hex format.
I get attached array which is not provide gps data.
Can you help me?
While I used another lib. I get some data and some is also wrong (another lib https://github.com/wsilence/gps_bones)
[decode.txt](https://github.com/uro/teltonika-fm-parser/files/6716486/decode.txt)

<?php

namespace Uro\TeltonikaFmParser;
include 'vendor/autoload.php';

$input = "00000000000000df08040000017a4350fcf800000000000000000000000000000000000a05f00050001505c800450205b50000b600001800004310b744000000000000017a4350d5e800000000000000000000000000000000000a05f00050001505c800450205b50000b600001800004310b744000000000000017a4350aed800000000000000000000000000000000000a05f00050041500c800450205b50000b600001800004310b744000000000000017a43502a0800000000000000000000000000000000000a05f00050001505c800450205b50000b600001800004310a54400000000040000eb76";

$payload = $input;
$parser = new FmParser('tcp');
$packet = $parser->decodeData($payload);
$packet = (array) $packet;

echo '<pre>';
print_r($packet);
exit;

**Comment by Nimesh-Soni** [comment]
hello anyone have decoder with TMT250 device

**Comment by uro** [comment]
This library is prepared to work with Teltonika FMB devices. Unfortunately, I don't have any TMT device to test.
