### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class "PhpBinaryReader\BinaryReader" not found

### ISSUE THREAD

**Issue by aungkoman** [uro/teltonika-fm-parser#8]
We did't found BinaryReader class. Where can we find this class?

**Comment by gricob** [comment]
BinaryReader is part of [mdurrant/php-binary-reader](https://github.com/mdurrant/php-binary-reader). It is installed via composer.

**Comment by aungkoman** [comment]
Thanks.
I forget to install binary reader library.
