### ISSUE TITLE
Received packet problems

### ISSUE THREAD

**Issue by g-soft** [uro/teltonika-fm-parser#9]
In the example 
         $payload = fread($conn, 1024);
If the packet is bigger than 1024 don't works fine

**Solution tested:**
		  
  $payload="";

				while( !feof( $conn ) ) {
			 $payload.=fread( $conn, 1024 ) ;
			}

**Comment by uro** [comment]
Hello @g-soft 

Would you like to submit pr with a fix?

**Comment by uro** [comment]
Hello @g-soft , 

Did you come to any solution with those?
